//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_de_clinicas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class consultas
    {
        public Boolean prueba { get; set; }
        public int idConsulta { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public Nullable<int> idMedico { get; set; }
        public Nullable<System.DateTime> fechaRealizacion { get; set; }
        public Nullable<float> costo { get; set; }
        public string descripcion { get; set; }
        public Nullable<float> costoMaterialesDescartables { get; set; }

        [Required(ErrorMessage = "Debe ingresar consultorio/practica")]
        [RegularExpression("(consultorio|consultorio |practica)", ErrorMessage = "Ingrese consultorio o practica")]

        public string tipoConsulta { get; set; }

        public virtual medicos medicos { get; set; }
        public virtual pacientes pacientes { get; set; }
    }
}
